package br.com.cervamania.cervamania.Model;

import br.com.cervamania.cervamania.R;

public class ImagensCervejas {

    public int retornaImagemCerveja(String nomeCerveja) {
        switch (nomeCerveja) {
            case "Dos Equis Lager Especial":        return R.drawable.lager1;
            case "Sol Premium Beer":                return R.drawable.lager2;
            case "Budweiser":                       return R.drawable.lager3;
            case "Almaza Pilsner Beer":             return R.drawable.lager4;
            case "Duff":                            return R.drawable.lager5;
            case "Baden Baden Cristal":             return R.drawable.lager6;
            case "Amstel":                          return R.drawable.lager7;
            case "DaDo Bier Original":              return R.drawable.lager8;
            case "Fosters":                         return R.drawable.lager9;
            case "Eisenbahn Natural":               return R.drawable.lager10;
            case "Germânia 55 Pilsen":              return R.drawable.lager11;
            case "Sagres":                          return R.drawable.lager12;
            case "Quilmes Cristal":                 return R.drawable.lager13;
            case "Corona Extra":                    return R.drawable.lager14;
            case "Norteña":                         return R.drawable.lager15;
            case "Schornstein Pilsen Natural":      return R.drawable.lager16;
            case "Brooklyn Lager":                  return R.drawable.lager18;
            case "Noi Bionda":                      return R.drawable.lager19;
            case "Moa Original":                    return R.drawable.lager20;
            case "Estrella Damm":                   return R.drawable.lager21;
            case "Backer Pilsen":                   return R.drawable.lager22;
            case "Mistura Clássica Pilsen":         return R.drawable.lager23;
            case "Serramalte":                      return R.drawable.lager24;
            case "Bierland Pilsen":                 return R.drawable.lager25;
            case "Beck´s":                          return R.drawable.lager26;
            case "Proibida Pilsen":                 return R.drawable.lager27;
            case "Proibida Puro Malte Leve":        return R.drawable.lager28;
            case "Jupiler":                         return R.drawable.lager29;
            case "Brewpoint Lager":                 return R.drawable.lager30;
            case "Brahma Extra Red Lager":          return R.drawable.amber1;
            case "Patagônia Amber Lager":           return R.drawable.amber2;
            case "Biritis":                         return R.drawable.vienna1;
            case "Primátor Polotmavy 13º":          return R.drawable.vienna2;
            case "Bohemia Aura Lager":              return R.drawable.vienna3;
            case "Bierland Vienna":                 return R.drawable.vienna4;
            case "1906 Reserva Especial":           return R.drawable.vienna5;
            case "Warsteiner Premium Verum":        return R.drawable.pilsener1;
            case "Paulaner Premium Pils":           return R.drawable.pilsener2;
            case "Amstel Premium Pilsener":         return R.drawable.pilsener3;
            case "Weihenstephaner Pilsner":         return R.drawable.pilsener4;
            case "Bitburger Premium Beer":          return R.drawable.pilsener5;
            case "Sagres Bohemia":                  return R.drawable.pilsener6;
            case "Sul Americana":                   return R.drawable.pilsener7;
            case "König Pilsener":                  return R.drawable.pilsener8;
            case "Patagônia Bohemian Pilsener":     return R.drawable.pilsener9;
            case "Primátor Premium 12º":            return R.drawable.pilsener10;
            case "Primátor Rytirsky":               return R.drawable.pilsener11;
            case "Ashby Pilsen":                    return R.drawable.pilsener12;
            case "Moa Methode":                     return R.drawable.pilsener13;
            case "Birra Del Borgo My Antonia":      return R.drawable.pilsener14;
            case "Old School Pilsen":               return R.drawable.pilsener15;
            case "Ashby Hops":                      return R.drawable.pilsener16;
            case "Irajá":                           return R.drawable.pilsener17;
            case "Wieninger Ruperti Pils":          return R.drawable.pilsener18;
            case "Zlato Prazske Lager":             return R.drawable.pilsener19;
            case "Wäls Bohemian Pilsner":           return R.drawable.pilsener20;
            case "X Wäls":                          return R.drawable.pilsener21;
            case "Brewpoint Pilsner":               return R.drawable.pilsener22;
            case "Stella Artois":                   return R.drawable.premium1;
            case "Heineken":                        return R.drawable.premium2;
            case "Estrella Galicia":                return R.drawable.premium3;
            case "Red Stripe":                      return R.drawable.premium4;
            case "Birra Moretti":                   return R.drawable.premium5;
            case "Cidade Imperial":                 return R.drawable.premium6;
            case "Coruja Otus Lager":               return R.drawable.premium7;
            case "Colorado Cauim":                  return R.drawable.premium8;
            case "Super Bock Classic":              return R.drawable.premium9;
            case "Carlsberg Pilsner":               return R.drawable.premium10;
            case "Paulistânia":                     return R.drawable.premium11;
            case "Bohemia Imperial":                return R.drawable.premium12;
            case "Eisenbahn Pilsen":                return R.drawable.premium13;
            case "Therezópolis Gold":               return R.drawable.premium14;
            case "Amstel Pulse":                    return R.drawable.premium15;
            case "DaDo Bier Lager":                 return R.drawable.premium16;
            case "Brahma Extra Lager":              return R.drawable.premium17;
            case "Cerpa Tijuca":                    return R.drawable.premium18;
            case "Cerpa Export":                    return R.drawable.premium19;
            case "Cacildis":                        return R.drawable.premium20;
            case "Noi Bionda Oro":                  return R.drawable.premium21;
            case "Faxe Premium":                    return R.drawable.premium22;
            case "Faxe Royal Export":               return R.drawable.premium23;
            case "Ravache Gold":                    return R.drawable.premium24;
            case "Insana Gold":                     return R.drawable.premium25;
            case "Miller Genuine Draft":            return R.drawable.premium26;
            case "Mohave Coyote":                   return R.drawable.premium27;
            case "Proibida Puro Malte":             return R.drawable.premium28;
            case "Antuérpia Premium Lager":         return R.drawable.premium29;
            case "Cerpa Prime":                     return R.drawable.premium30;
            case "Weihenstephaner Original":        return R.drawable.helles1;
            case "Hofbräu Original":                return R.drawable.helles2;
            case "Paulaner Original Münchner Hell": return R.drawable.helles3;
            case "Cidade Imperial Helles Munchen":  return R.drawable.helles4;
            case "Coruja Strix Extra":              return R.drawable.helles5;
            case "Spaten Hell":                     return R.drawable.helles6;
            case "Hacker Pschorr Munich Gold":      return R.drawable.helles7;
            case "Weltenburger Kloster Urtyp Hell": return R.drawable.helles8;
            case "Löwenbräu Original":              return R.drawable.helles9;
            case "Wieninger Teisendorfer Hell":     return R.drawable.helles10;
            case "Hofbräu Dunkel":                  return R.drawable.dunkel1;
            case "König Ludwig Dunkel":             return R.drawable.dunkel2;
            case "Paulistânia Escura":              return R.drawable.dunkel3;
            case "Therezópolis Ebenholz":           return R.drawable.dunkel4;
            case "Weihenstephaner Tradition Bayrisch Dunkel": return R.drawable.dunkel5;
            case "Warsteiner Premium Dunkel":       return R.drawable.dunkel6;
            case "Sagres Preta":                    return R.drawable.dunkel7;
            case "Ravache Munich Dunkel":           return R.drawable.dunkel8;
            case "Weltenburger Kloster Barock Dunkel": return R.drawable.dunkel9;
            case "1906 Black Coupage":              return R.drawable.dunkel10;
            case "Brewpoint Dunkel":                return R.drawable.dunkel11;
            case "Antuérpia Munich Dunkel":         return R.drawable.dunkel12;
            case "Coruja Noctua Extra Dark Lager":  return R.drawable.darklager1;
            case "Stella Artois Noire":             return R.drawable.darklager2;
            case "Brahma Black":                    return R.drawable.darklager3;
            case "Itaipava Black":                  return R.drawable.darklager4;
            case "Ashby Hops Escura":               return R.drawable.darklager5;
            case "Noi Nera":                        return R.drawable.schwarzbier1;
            case "Eisenbahn Dunkel":                return R.drawable.schwarzbier2;
            case "Faxe Black":                      return R.drawable.schwarzbier3;
            case "Cidade Imperial Dunkel":          return R.drawable.schwarzbier4;
            case "Bohemia Escura":                  return R.drawable.schwarzbier5;
            case "Therezópolis Rubine":             return R.drawable.bock1;
            case "Baden Baden Bock":                return R.drawable.bock2;
            case "Schornstein Bock":                return R.drawable.bock3;
            case "Bierland Bock":                   return R.drawable.bock4;
            case "Brewpoint Bock":                  return R.drawable.bock5;
            case "Riegele Speziator":               return R.drawable.doppelbock1;
            case "Paulaner Salvator":               return R.drawable.doppelbock2;
            case "Wieninger Impulsator":            return R.drawable.doppelbock3;
            case "Júpiter American Pale Ale":       return R.drawable.apa1;
            case "Devassa Ruiva":                   return R.drawable.apa2;
            case "Brooklyn American Ale":           return R.drawable.apa3;
            case "Therezópolis Copper":             return R.drawable.apa4;
            case "Moa Pale Ale":                    return R.drawable.apa5;
            case "Insana American Pale Ale":        return R.drawable.apa6;
            case "Hocus Pocus APA Cadabra":         return R.drawable.apa7;
            case "Baden Baden Golden":              return R.drawable.apa8;
            case "Fura Olho":                       return R.drawable.apa9;
            case "Ashby American Pale Ale":         return R.drawable.apa10;
            case "Fuller´s Wild River":             return R.drawable.apa11;
            case "Coruja Otus Hop":                 return R.drawable.apa12;
            case "Andaraí":                         return R.drawable.apa13;
            case "Wäls Verano":                     return R.drawable.apa14;
            case "Batemans Combined Harvest":       return R.drawable.bitter1;
            case "Goose Island Honkers Ale":        return R.drawable.bitter2;
            case "Fuller´s London Pride":           return R.drawable.bitter3;
            case "Backer Pale Ale":                 return R.drawable.bitter4;
            case "Bohemia 838 Pale Ale":            return R.drawable.bitter5;
            case "Bierland English Pale Ale":       return R.drawable.bitter6;
            case "Ashby British Pale Ale":          return R.drawable.bitter7;
            case "Fuller´s ESB":                    return R.drawable.bitter8;
            case "La Trappe Isid´or":               return R.drawable.bpa1;
            case "Birra Moretti Grand Cru":         return R.drawable.bpa2;
            case "Eisenbahn Pale Ale":              return R.drawable.bpa3;
            case "Ashby Pale Ale Extra":            return R.drawable.bpa4;
            case "Noi Avena":                       return R.drawable.bpa5;
            case "Gauloise Ambrée":                 return R.drawable.bpa6;
            case "Leffe Blonde":                    return R.drawable.bba1;
            case "La Trappe Blond":                 return R.drawable.bba2;
            case "Chimay Dorée (Gold)":             return R.drawable.bba3;
            case "Bohemia Caá-Yari":                return R.drawable.bba4;
            case "Kasteel Blond":                   return R.drawable.bba5;
            case "St. Feuillien Blonde":            return R.drawable.bba6;
            case "Gauloise Blonde":                 return R.drawable.bba7;
            case "Three Monkeys Golden Ale":        return R.drawable.bba8;
            case "Fraga Blonde":                    return R.drawable.bba9;
            case "Trópica Bora Bora":               return R.drawable.bba10;
            case "Maredsous 6 Blond":               return R.drawable.bba11;
            case "Zupa":                            return R.drawable.bba12;
            case "Bierland Belgian Blond Ale":      return R.drawable.bba13;
            case "Old School Belgian Blond":        return R.drawable.bba14;
            case "Barraqueira":                     return R.drawable.bba15;
            case "Leuven Golden Ale":               return R.drawable.bba16;
            case "Mohave Bandita":                  return R.drawable.bba17;
            case "Gouden Carolus Hopsinjoor":       return R.drawable.special1;
            case "La Chouffe":                      return R.drawable.special2;
            case "Mc Chouffe":                      return R.drawable.special3;
            case "Baden Baden Chocolate":           return R.drawable.special4;
            case "Hoegaarden Verboden Vrucht":      return R.drawable.special5;
            case "Therezópolis Jade":               return R.drawable.ipa1;
            case "Júpiter India Pale Ale":          return R.drawable.ipa2;
            case "Schornstein India Pale Ale":      return R.drawable.ipa3;
            case "Colorado Indica":                 return R.drawable.ipa4;
            case "Wensky Beer Curupira":            return R.drawable.ipa5;
            case "Invicta 1000 IBU":                return R.drawable.ipa6;
            case "3 Lobos Pele Vermelha":           return R.drawable.ipa7;
            case "Baden Baden American IPA":        return R.drawable.ipa8;
            case "Dado Bier IPA":                   return R.drawable.ipa9;
            case "Brooklyn East IPA":               return R.drawable.ipa10;
            case "Goose Island IPA":                return R.drawable.ipa11;
            case "Noi Amara":                       return R.drawable.ipa12;
            case "Bohemia Jabutipa":                return R.drawable.ipa13;
            case "Vedett Extra Ordinary IPA":       return R.drawable.ipa14;
            case "Kasteel Hoppy":                   return R.drawable.ipa15;
            case "Three Monkeys India White Ale":   return R.drawable.ipa16;
            case "Roleta Russa Imperial IPA":       return R.drawable.ipa17;
            case "Roleta Russa IPA":                return R.drawable.ipa18;
            case "Roleta Russa Black IPA":          return R.drawable.ipa19;
            case "Fraga IPA":                       return R.drawable.ipa20;
            case "Mistura Clássica Vertigem":       return R.drawable.ipa21;
            case "Mistura Clássica Amnésia":        return R.drawable.ipa22;
            case "Hocus Pocus Interstellar":        return R.drawable.ipa23;
            case "Trópica Arequipa":                return R.drawable.ipa24;
            case "Bierland IPA":                    return R.drawable.ipa25;
            case "Birra del Borgo Reale":           return R.drawable.ipa26;
            case "Birra del Borgo Reale Extra":     return R.drawable.ipa27;
            case "Colorado Eugênia":                return R.drawable.ipa28;
            case "Colorado Vixnu":                  return R.drawable.ipa29;
            case "Colorado Nassau":                 return R.drawable.ipa30;
            case "Old School IPA":                  return R.drawable.ipa31;
            case "Cerol Fininho":                   return R.drawable.ipa32;
            case "Pipa Voada":                      return R.drawable.ipa33;
            case "Cerol Bala":                      return R.drawable.ipa34;
            case "Alquimia #1":                     return R.drawable.ipa35;
            case "Leuven Belgian IPA":              return R.drawable.ipa36;
            case "Ashby IPA Nirvana":               return R.drawable.ipa37;
            case "Fuller´s Indian Pale Ale":        return R.drawable.ipa38;
            case "Mohave Diablo":                   return R.drawable.ipa39;
            case "Marechal":                        return R.drawable.ipa40;
            case "Faxe IPA":                        return R.drawable.ipa41;
            case "Brewpoint IPA":                   return R.drawable.ipa42;
            case "Antuérpia American Ipa":          return R.drawable.ipa43;
            case "St. Gallen Red Ale":              return R.drawable.redale1;
            case "Noi Rossa":                       return R.drawable.redale2;
            case "Baden Baden Red Ale":             return R.drawable.redale3;
            case "Bierland American Red Ale":       return R.drawable.redale4;
            case "Old School Red Ale":              return R.drawable.redale5;
            case "Leuven Red Ale":                  return R.drawable.redale6;
            case "Antuérpia Irish Red Ale":         return R.drawable.redale7;
            case "Brooklyn Brown Ale":              return R.drawable.brown1;
            case "Three Monkeys Brownie Ale":       return R.drawable.brown2;
            case "Fraga Brown":                     return R.drawable.brown3;
            case "Backer Brown":                    return R.drawable.brown4;
            case "Colorado Berthô":                 return R.drawable.brown5;
            case "Leffe Brune":                     return R.drawable.dubbel1;
            case "Chimay Red Cap":                  return R.drawable.dubbel2;
            case "La Trappe Dubbel":                return R.drawable.dubbel3;
            case "Bohemia Confraria":               return R.drawable.dubbel4;
            case "Westmalle Dubbel":                return R.drawable.dubbel5;
            case "Wäls Dubbel":                     return R.drawable.dubbel6;
            case "St. Feuillien Brune":             return R.drawable.dubbel7;
            case "Gauloise Bruin":                  return R.drawable.dubbel8;
            case "Hertog Jan Dubbel":               return R.drawable.dubbel9;
            case "Trappistes Rochefort 6":          return R.drawable.dubbel10;
            case "Leuven Dubbel":                   return R.drawable.dubbel11;
            case "Gouden Carolus Tripel":           return R.drawable.tripel1;
            case "Chimay Triple":                   return R.drawable.tripel2;
            case "La Trappe Tripel":                return R.drawable.tripel3;
            case "Leffe Tripel":                    return R.drawable.tripel4;
            case "Westmalle Tripel":                return R.drawable.tripel5;
            case "Wäls Trippel":                    return R.drawable.tripel6;
            case "Therezópolis Diamant":            return R.drawable.tripel7;
            case "Kasteel Tripel":                  return R.drawable.tripel8;
            case "St. Feuillien Tripel":            return R.drawable.tripel9;
            case "Mistura Clássica Beatus":         return R.drawable.tripel10;
            case "Trópica Veracruz":                return R.drawable.tripel11;
            case "Hertog Jan Tripel":               return R.drawable.tripel12;
            case "Baden Baden Tripel":              return R.drawable.tripel13;
            case "Tripel Karmeliet":                return R.drawable.tripel14;
            case "Maredsous 10 Tripel":             return R.drawable.tripel15;
            case "Antuérpia Belgian Tripel":        return R.drawable.tripel16;
            case "La Trappe Quadrupel":             return R.drawable.quadrupel1;
            case "Trappistes Rochefort 10":         return R.drawable.quadrupel2;
            case "Wäls Quadrupel":                  return R.drawable.quadrupel3;
            case "Gouden Carolus Cuvée van de Keizer Rood": return R.drawable.golden1;
            case "Delirium Tremens":                return R.drawable.golden2;
            case "Hoegaarden Grand Cru":            return R.drawable.golden3;
            case "La Guillotine":                   return R.drawable.golden4;
            case "Duvel":                           return R.drawable.golden5;
            case "Leffe 9º (Rituel 9)":             return R.drawable.golden6;
            case "Eisenbahn Strong Golden Ale":     return R.drawable.golden7;
            case "DaDo Bier Belgian Ale":           return R.drawable.golden8;
            case "Ashby Ale Forte":                 return R.drawable.golden9;
            case "Piraat":                          return R.drawable.golden10;
            case "Hocus Pocus Magic Trap":          return R.drawable.golden11;
            case "Bierland Strong Golden Ale":      return R.drawable.golden12;
            case "Birra del Borgo Stelle&Strisce":  return R.drawable.golden13;
            case "Birra del Borgo Cortigiana":      return R.drawable.golden14;
            case "Chimay Blue Cap":                 return R.drawable.darkale1;
            case "Gouden Carolus Classic":          return R.drawable.darkale2;
            case "Delirium Nocturnum":              return R.drawable.darkale3;
            case "Leffe Radieuse":                  return R.drawable.darkale4;
            case "La Trappe Jubilaris":             return R.drawable.darkale5;
            case "Gouden Carolus Ambrio":           return R.drawable.darkale6;
            case "Leffe Royale":                    return R.drawable.darkale7;
            case "Kasteel Donker":                  return R.drawable.darkale8;
            case "Gulden Draak":                    return R.drawable.darkale9;
            case "Hertog Jan Grand Prestige":       return R.drawable.darkale10;
            case "Trappistes Rochefort 8":          return R.drawable.darkale11;
            case "Maredsous 8 Bruin":               return R.drawable.darkale13;
            case "Birra del Borgo Maledetta":       return R.drawable.darkale14;
            case "Weihenstephaner Hefe Weissbier":  return R.drawable.weissbier1;
            case "Edelweiss Weissbier-Hefetrüb":    return R.drawable.weissbier2;
            case "Paulaner Hefe-Weissbier Naturtrüb": return R.drawable.weissbier3;
            case "Hofbräu Münchner Weisse":         return R.drawable.weissbier4;
            case "Therezopolis Elfenbein":          return R.drawable.weissbier5;
            case "Noi Bianca":                      return R.drawable.weissbier6;
            case "St. Gallen Weissbier":            return R.drawable.weissbier7;
            case "Baden Baden Weiss":               return R.drawable.weissbier8;
            case "Eisenbahn Weizenbier":            return R.drawable.weissbier9;
            case "Erdinger Weissbier":              return R.drawable.weissbier10;
            case "Colorado Appia":                  return R.drawable.weissbier11;
            case "Bohemia Weiss":                   return R.drawable.weissbier12;
            case "DaDo Bier Weiss":                 return R.drawable.weissbier13;
            case "Schornstein Weiss":               return R.drawable.weissbier14;
            case "Patagônia Weissbier":             return R.drawable.weissbier15;
            case "Primátor Weizenbier":             return R.drawable.weissbier16;
            case "Riegele´s Weisse":                return R.drawable.weissbier17;
            case "Ashby Weiss":                     return R.drawable.weissbier18;
            case "Brooklyn Wheat Beer":             return R.drawable.weissbier19;
            case "Coruja Alba Weizen":              return R.drawable.weissbier20;
            case "Moa Blanc":                       return R.drawable.weissbier21;
            case "Insana Weizen":                   return R.drawable.weissbier22;
            case "Fraga Weiss":                     return R.drawable.weissbier23;
            case "Backer Trigo":                    return R.drawable.weissbier24;
            case "Mistura Clássica Matilda":        return R.drawable.weissbier25;
            case "Bohemia 14 Weiss":                return R.drawable.weissbier26;
            case "Erdinger Urweisse":               return R.drawable.weissbier27;
            case "Brahma Extra Weiss":              return R.drawable.weissbier28;
            case "Franziskaner Hefe-Weissbier Naturtrüb": return R.drawable.weissbier29;
            case "Bierland Weizen":                 return R.drawable.weissbier30;
            case "Hacker Pschorr Weisse":           return R.drawable.weissbier31;
            case "Old School Weiss":                return R.drawable.weissbier32;
            case "Lado A":                          return R.drawable.weissbier33;
            case "Lado B":                          return R.drawable.weissbier34;
            case "Wieninger Hefe Weissbier":        return R.drawable.weissbier35;
            case "Brewpoint Weiss":                 return R.drawable.weissbier36;
            case "Antuérpia Weissbier":             return R.drawable.weissbier37;
            case "Riegele´s Augustus":              return R.drawable.weizenbock1;
            case "Erdinger Pikantus":               return R.drawable.weizenbock2;
            case "Zapp":                            return R.drawable.weizenbock3;
            case "Coruja Alba Weizenbock":          return R.drawable.weizenbock4;
            case "Erdinger Weissbier Dunkel":       return R.drawable.dunkelweizen1;
            case "Paulaner Hefe-Weissbier Dunkel":  return R.drawable.dunkelweizen2;
            case "Franziskaner Hefe-Weissbier Dunkel": return R.drawable.dunkelweizen3;
            case "Weltenburger Kloster Hefe-Weissbier Dunkel": return R.drawable.dunkelweizen4;
            case "Hoegaarden":                      return R.drawable.witbier1;
            case "DiTriguis":                       return R.drawable.witbier2;
            case "Bohemia Bela Rosa":               return R.drawable.witbier3;
            case "Therezópolis Or Blanc":           return R.drawable.witbier4;
            case "Vedett Extra White":              return R.drawable.witbier5;
            case "Faxe Witbier":                    return R.drawable.witbier6;
            case "Schornstein Witbier":             return R.drawable.witbier7;
            case "Baden Baden Witbier":             return R.drawable.witbier8;
            case "Wäls Witte":                      return R.drawable.witbier9;
            case "Blanche de Bruxelles":            return R.drawable.witbier10;
            case "Bierland Witbier":                return R.drawable.witbier11;
            case "Old School Witbier":              return R.drawable.witbier12;
            case "Leuven Blanche":                  return R.drawable.witbier13;
            case "Leuven Witbier":                  return R.drawable.witbier14;
            case "Mohave Yucca":                    return R.drawable.witbier15;
            case "Praya Witbier":                   return R.drawable.witbier16;
            case "Guinness Draught":                return R.drawable.stout1;
            case "Schornstein Imperial Stout":      return R.drawable.stout2;
            case "Baden Baden Stout":               return R.drawable.stout3;
            case "Murphy´s Draught Irish Stout":    return R.drawable.stout4;
            case "Super Bock Stout":                return R.drawable.stout5;
            case "Wensky Beer Lobisomem":           return R.drawable.stout6;
            case "St. Gallen Stout Porter":         return R.drawable.stout7;
            case "Colorado Ithaca":                 return R.drawable.stout8;
            case "Primátor Stout":                  return R.drawable.stout9;
            case "Noi Cioccolato":                  return R.drawable.stout10;
            case "Moa Imperial Stout":              return R.drawable.stout11;
            case "Mistura Clássica Panhead":        return R.drawable.stout12;
            case "Bohemia Oito e Um":               return R.drawable.stout13;
            case "Wäls Petroleum":                  return R.drawable.stout14;
            case "Bierland Russian Imperial Stout": return R.drawable.stout15;
            case "Fuller´s Black Cab Stout":        return R.drawable.stout16;
            case "Fuller´s Imperial Stout":         return R.drawable.stout17;
            case "Colorado Demoiselle":             return R.drawable.porter1;
            case "3 Lobos Bravo":                   return R.drawable.porter2;
            case "Ashby Porter":                    return R.drawable.porter3;
            case "Insana Chocolate Porter":         return R.drawable.porter4;
            case "Trópica Macau":                   return R.drawable.porter5;
            case "Double Zuzi":                     return R.drawable.porter6;
            case "Fuller´s London Porter":          return R.drawable.porter7;

            default: return R.drawable.ic_not_founddark;
        }

    }

    public int retornaImagemCervejaReduzida(String nomeCerveja) {
        switch (nomeCerveja) {
            case "Dos Equis Lager Especial":        return R.drawable.lager1reduzida;
            case "Sol Premium Beer":                return R.drawable.lager2reduzida;
            case "Budweiser":                       return R.drawable.lager3reduzida;
            case "Almaza Pilsner Beer":             return R.drawable.lager4reduzida;
            case "Duff":                            return R.drawable.lager5reduzida;
            case "Baden Baden Cristal":             return R.drawable.lager6reduzida;
            case "Amstel":                          return R.drawable.lager7reduzida;
            case "DaDo Bier Original":              return R.drawable.lager8reduzida;
            case "Fosters":                         return R.drawable.lager9reduzida;
            case "Eisenbahn Natural":               return R.drawable.lager10reduzida;
            case "Germânia 55 Pilsen":              return R.drawable.lager11reduzida;
            case "Sagres":                          return R.drawable.lager12reduzida;
            case "Quilmes Cristal":                 return R.drawable.lager13reduzida;
            case "Corona Extra":                    return R.drawable.lager14reduzida;
            case "Norteña":                         return R.drawable.lager15reduzida;
            case "Schornstein Pilsen Natural":      return R.drawable.lager16reduzida;
            case "Brooklyn Lager":                  return R.drawable.lager18reduzida;
            case "Noi Bionda":                      return R.drawable.lager19reduzida;
            case "Moa Original":                    return R.drawable.lager20reduzida;
            case "Estrella Damm":                   return R.drawable.lager21reduzida;
            case "Backer Pilsen":                   return R.drawable.lager22reduzida;
            case "Mistura Clássica Pilsen":         return R.drawable.lager23reduzida;
            case "Serramalte":                      return R.drawable.lager24reduzida;
            case "Bierland Pilsen":                 return R.drawable.lager25reduzida;
            case "Beck´s":                          return R.drawable.lager26reduzida;
            case "Proibida Pilsen":                 return R.drawable.lager27reduzida;
            case "Proibida Puro Malte Leve":        return R.drawable.lager28reduzida;
            case "Jupiler":                         return R.drawable.lager29reduzida;
            case "Brewpoint Lager":                 return R.drawable.lager30reduzida;
            case "Brahma Extra Red Lager":          return R.drawable.amber1reduzida;
            case "Patagônia Amber Lager":           return R.drawable.amber2reduzida;
            case "Biritis":                         return R.drawable.vienna1reduzida;
            case "Primátor Polotmavy 13º":          return R.drawable.vienna2reduzida;
            case "Bohemia Aura Lager":              return R.drawable.vienna3reduzida;
            case "Bierland Vienna":                 return R.drawable.vienna4reduzida;
            case "1906 Reserva Especial":           return R.drawable.vienna5reduzida;
            case "Warsteiner Premium Verum":        return R.drawable.pilsener1reduzida;
            case "Paulaner Premium Pils":           return R.drawable.pilsener2reduzida;
            case "Amstel Premium Pilsener":         return R.drawable.pilsener3reduzida;
            case "Weihenstephaner Pilsner":         return R.drawable.pilsener4reduzida;
            case "Bitburger Premium Beer":          return R.drawable.pilsener5reduzida;
            case "Sagres Bohemia":                  return R.drawable.pilsener6reduzida;
            case "Sul Americana":                   return R.drawable.pilsener7reduzida;
            case "König Pilsener":                  return R.drawable.pilsener8reduzida;
            case "Patagônia Bohemian Pilsener":     return R.drawable.pilsener9reduzida;
            case "Primátor Premium 12º":            return R.drawable.pilsener10reduzida;
            case "Primátor Rytirsky":               return R.drawable.pilsener11reduzida;
            case "Ashby Pilsen":                    return R.drawable.pilsener12reduzida;
            case "Moa Methode":                     return R.drawable.pilsener13reduzida;
            case "Birra Del Borgo My Antonia":      return R.drawable.pilsener14reduzida;
            case "Old School Pilsen":               return R.drawable.pilsener15reduzida;
            case "Ashby Hops":                      return R.drawable.pilsener16reduzida;
            case "Irajá":                           return R.drawable.pilsener17reduzida;
            case "Wieninger Ruperti Pils":          return R.drawable.pilsener18reduzida;
            case "Zlato Prazske Lager":             return R.drawable.pilsener19reduzida;
            case "Wäls Bohemian Pilsner":           return R.drawable.pilsener20reduzida;
            case "X Wäls":                          return R.drawable.pilsener21reduzida;
            case "Brewpoint Pilsner":               return R.drawable.pilsener22reduzida;
            case "Stella Artois":                   return R.drawable.premium1reduzida;
            case "Heineken":                        return R.drawable.premium2reduzida;
            case "Estrella Galicia":                return R.drawable.premium3reduzida;
            case "Red Stripe":                      return R.drawable.premium4reduzida;
            case "Birra Moretti":                   return R.drawable.premium5reduzida;
            case "Cidade Imperial":                 return R.drawable.premium6reduzida;
            case "Coruja Otus Lager":               return R.drawable.premium7reduzida;
            case "Colorado Cauim":                  return R.drawable.premium8reduzida;
            case "Super Bock Classic":              return R.drawable.premium9reduzida;
            case "Carlsberg Pilsner":               return R.drawable.premium10reduzida;
            case "Paulistânia":                     return R.drawable.premium11reduzida;
            case "Bohemia Imperial":                return R.drawable.premium12reduzida;
            case "Eisenbahn Pilsen":                return R.drawable.premium13reduzida;
            case "Therezópolis Gold":               return R.drawable.premium14reduzida;
            case "Amstel Pulse":                    return R.drawable.premium15reduzida;
            case "DaDo Bier Lager":                 return R.drawable.premium16reduzida;
            case "Brahma Extra Lager":              return R.drawable.premium17reduzida;
            case "Cerpa Tijuca":                    return R.drawable.premium18reduzida;
            case "Cerpa Export":                    return R.drawable.premium19reduzida;
            case "Cacildis":                        return R.drawable.premium20reduzida;
            case "Noi Bionda Oro":                  return R.drawable.premium21reduzida;
            case "Faxe Premium":                    return R.drawable.premium22reduzida;
            case "Faxe Royal Export":               return R.drawable.premium23reduzida;
            case "Ravache Gold":                    return R.drawable.premium24reduzida;
            case "Insana Gold":                     return R.drawable.premium25reduzida;
            case "Miller Genuine Draft":            return R.drawable.premium26reduzida;
            case "Mohave Coyote":                   return R.drawable.premium27reduzida;
            case "Proibida Puro Malte":             return R.drawable.premium28reduzida;
            case "Antuérpia Premium Lager":         return R.drawable.premium29reduzida;
            case "Cerpa Prime":                     return R.drawable.premium30reduzida;
            case "Weihenstephaner Original":        return R.drawable.helles1reduzida;
            case "Hofbräu Original":                return R.drawable.helles2reduzida;
            case "Paulaner Original Münchner Hell": return R.drawable.helles3reduzida;
            case "Cidade Imperial Helles Munchen":  return R.drawable.helles4reduzida;
            case "Coruja Strix Extra":              return R.drawable.helles5reduzida;
            case "Spaten Hell":                     return R.drawable.helles6reduzida;
            case "Hacker Pschorr Munich Gold":      return R.drawable.helles7reduzida;
            case "Weltenburger Kloster Urtyp Hell": return R.drawable.helles8reduzida;
            case "Löwenbräu Original":              return R.drawable.helles9reduzida;
            case "Wieninger Teisendorfer Hell":     return R.drawable.helles10reduzida;
            case "Hofbräu Dunkel":                  return R.drawable.dunkel1reduzida;
            case "König Ludwig Dunkel":             return R.drawable.dunkel2reduzida;
            case "Paulistânia Escura":              return R.drawable.dunkel3reduzida;
            case "Therezópolis Ebenholz":           return R.drawable.dunkel4reduzida;
            case "Weihenstephaner Tradition Bayrisch Dunkel": return R.drawable.dunkel5reduzida;
            case "Warsteiner Premium Dunkel":       return R.drawable.dunkel6reduzida;
            case "Sagres Preta":                    return R.drawable.dunkel7reduzida;
            case "Ravache Munich Dunkel":           return R.drawable.dunkel8reduzida;
            case "Weltenburger Kloster Barock Dunkel": return R.drawable.dunkel9reduzida;
            case "1906 Black Coupage":              return R.drawable.dunkel10reduzida;
            case "Brewpoint Dunkel":                return R.drawable.dunkel11reduzida;
            case "Antuérpia Munich Dunkel":         return R.drawable.dunkel12reduzida;
            case "Coruja Noctua Extra Dark Lager":  return R.drawable.darklager1reduzida;
            case "Stella Artois Noire":             return R.drawable.darklager2reduzida;
            case "Brahma Black":                    return R.drawable.darklager3reduzida;
            case "Itaipava Black":                  return R.drawable.darklager4reduzida;
            case "Ashby Hops Escura":               return R.drawable.darklager5reduzida;
            case "Noi Nera":                        return R.drawable.schwarzbier1reduzida;
            case "Eisenbahn Dunkel":                return R.drawable.schwarzbier2reduzida;
            case "Faxe Black":                      return R.drawable.schwarzbier3reduzida;
            case "Cidade Imperial Dunkel":          return R.drawable.schwarzbier4reduzida;
            case "Bohemia Escura":                  return R.drawable.schwarzbier5reduzida;
            case "Therezópolis Rubine":             return R.drawable.bock1reduzida;
            case "Baden Baden Bock":                return R.drawable.bock2reduzida;
            case "Schornstein Bock":                return R.drawable.bock3reduzida;
            case "Bierland Bock":                   return R.drawable.bock4reduzida;
            case "Brewpoint Bock":                  return R.drawable.bock5reduzida;
            case "Riegele Speziator":               return R.drawable.doppelbock1reduzida;
            case "Paulaner Salvator":               return R.drawable.doppelbock2reduzida;
            case "Wieninger Impulsator":            return R.drawable.doppelbock3reduzida;
            case "Júpiter American Pale Ale":       return R.drawable.apa1reduzida;
            case "Devassa Ruiva":                   return R.drawable.apa2reduzida;
            case "Brooklyn American Ale":           return R.drawable.apa3reduzida;
            case "Therezópolis Copper":             return R.drawable.apa4reduzida;
            case "Moa Pale Ale":                    return R.drawable.apa5reduzida;
            case "Insana American Pale Ale":        return R.drawable.apa6reduzida;
            case "Hocus Pocus APA Cadabra":         return R.drawable.apa7reduzida;
            case "Baden Baden Golden":              return R.drawable.apa8reduzida;
            case "Fura Olho":                       return R.drawable.apa9reduzida;
            case "Ashby American Pale Ale":         return R.drawable.apa10reduzida;
            case "Fuller´s Wild River":             return R.drawable.apa11reduzida;
            case "Coruja Otus Hop":                 return R.drawable.apa12reduzida;
            case "Andaraí":                         return R.drawable.apa13reduzida;
            case "Wäls Verano":                     return R.drawable.apa14reduzida;
            case "Batemans Combined Harvest":       return R.drawable.bitter1reduzida;
            case "Goose Island Honkers Ale":        return R.drawable.bitter2reduzida;
            case "Fuller´s London Pride":           return R.drawable.bitter3reduzida;
            case "Backer Pale Ale":                 return R.drawable.bitter4reduzida;
            case "Bohemia 838 Pale Ale":            return R.drawable.bitter5reduzida;
            case "Bierland English Pale Ale":       return R.drawable.bitter6reduzida;
            case "Ashby British Pale Ale":          return R.drawable.bitter7reduzida;
            case "Fuller´s ESB":                    return R.drawable.bitter8reduzida;
            case "La Trappe Isid´or":               return R.drawable.bpa1reduzida;
            case "Birra Moretti Grand Cru":         return R.drawable.bpa2reduzida;
            case "Eisenbahn Pale Ale":              return R.drawable.bpa3reduzida;
            case "Ashby Pale Ale Extra":            return R.drawable.bpa4reduzida;
            case "Noi Avena":                       return R.drawable.bpa5reduzida;
            case "Gauloise Ambrée":                 return R.drawable.bpa6reduzida;
            case "Leffe Blonde":                    return R.drawable.bba1reduzida;
            case "La Trappe Blond":                 return R.drawable.bba2reduzida;
            case "Chimay Dorée (Gold)":             return R.drawable.bba3reduzida;
            case "Bohemia Caá-Yari":                return R.drawable.bba4reduzida;
            case "Kasteel Blond":                   return R.drawable.bba5reduzida;
            case "St. Feuillien Blonde":            return R.drawable.bba6reduzida;
            case "Gauloise Blonde":                 return R.drawable.bba7reduzida;
            case "Three Monkeys Golden Ale":        return R.drawable.bba8reduzida;
            case "Fraga Blonde":                    return R.drawable.bba9reduzida;
            case "Trópica Bora Bora":               return R.drawable.bba10reduzida;
            case "Maredsous 6 Blond":               return R.drawable.bba11reduzida;
            case "Zupa":                            return R.drawable.bba12reduzida;
            case "Bierland Belgian Blond Ale":      return R.drawable.bba13reduzida;
            case "Old School Belgian Blond":        return R.drawable.bba14reduzida;
            case "Barraqueira":                     return R.drawable.bba15reduzida;
            case "Leuven Golden Ale":               return R.drawable.bba16reduzida;
            case "Mohave Bandita":                  return R.drawable.bba17reduzida;
            case "Gouden Carolus Hopsinjoor":       return R.drawable.special1reduzida;
            case "La Chouffe":                      return R.drawable.special2reduzida;
            case "Mc Chouffe":                      return R.drawable.special3reduzida;
            case "Baden Baden Chocolate":           return R.drawable.special4reduzida;
            case "Hoegaarden Verboden Vrucht":      return R.drawable.special5reduzida;
            case "Therezópolis Jade":               return R.drawable.ipa1reduzida;
            case "Júpiter India Pale Ale":          return R.drawable.ipa2reduzida;
            case "Schornstein India Pale Ale":      return R.drawable.ipa3reduzida;
            case "Colorado Indica":                 return R.drawable.ipa4reduzida;
            case "Wensky Beer Curupira":            return R.drawable.ipa5reduzida;
            case "Invicta 1000 IBU":                return R.drawable.ipa6reduzida;
            case "3 Lobos Pele Vermelha":           return R.drawable.ipa7reduzida;
            case "Baden Baden American IPA":        return R.drawable.ipa8reduzida;
            case "Dado Bier IPA":                   return R.drawable.ipa9reduzida;
            case "Brooklyn East IPA":               return R.drawable.ipa10reduzida;
            case "Goose Island IPA":                return R.drawable.ipa11reduzida;
            case "Noi Amara":                       return R.drawable.ipa12reduzida;
            case "Bohemia Jabutipa":                return R.drawable.ipa13reduzida;
            case "Vedett Extra Ordinary IPA":       return R.drawable.ipa14reduzida;
            case "Kasteel Hoppy":                   return R.drawable.ipa15reduzida;
            case "Three Monkeys India White Ale":   return R.drawable.ipa16reduzida;
            case "Roleta Russa Imperial IPA":       return R.drawable.ipa17reduzida;
            case "Roleta Russa IPA":                return R.drawable.ipa18reduzida;
            case "Roleta Russa Black IPA":          return R.drawable.ipa19reduzida;
            case "Fraga IPA":                       return R.drawable.ipa20reduzida;
            case "Mistura Clássica Vertigem":       return R.drawable.ipa21reduzida;
            case "Mistura Clássica Amnésia":        return R.drawable.ipa22reduzida;
            case "Hocus Pocus Interstellar":        return R.drawable.ipa23reduzida;
            case "Trópica Arequipa":                return R.drawable.ipa24reduzida;
            case "Bierland IPA":                    return R.drawable.ipa25reduzida;
            case "Birra del Borgo Reale":           return R.drawable.ipa26reduzida;
            case "Birra del Borgo Reale Extra":     return R.drawable.ipa27reduzida;
            case "Colorado Eugênia":                return R.drawable.ipa28reduzida;
            case "Colorado Vixnu":                  return R.drawable.ipa29reduzida;
            case "Colorado Nassau":                 return R.drawable.ipa30reduzida;
            case "Old School IPA":                  return R.drawable.ipa31reduzida;
            case "Cerol Fininho":                   return R.drawable.ipa32reduzida;
            case "Pipa Voada":                      return R.drawable.ipa33reduzida;
            case "Cerol Bala":                      return R.drawable.ipa34reduzida;
            case "Alquimia #1":                     return R.drawable.ipa35reduzida;
            case "Leuven Belgian IPA":              return R.drawable.ipa36reduzida;
            case "Ashby IPA Nirvana":               return R.drawable.ipa37reduzida;
            case "Fuller´s Indian Pale Ale":        return R.drawable.ipa38reduzida;
            case "Mohave Diablo":                   return R.drawable.ipa39reduzida;
            case "Marechal":                        return R.drawable.ipa40reduzida;
            case "Faxe IPA":                        return R.drawable.ipa41reduzida;
            case "Brewpoint IPA":                   return R.drawable.ipa42reduzida;
            case "Antuérpia American Ipa":          return R.drawable.ipa43reduzida;
            case "St. Gallen Red Ale":              return R.drawable.redale1reduzida;
            case "Noi Rossa":                       return R.drawable.redale2reduzida;
            case "Baden Baden Red Ale":             return R.drawable.redale3reduzida;
            case "Bierland American Red Ale":       return R.drawable.redale4reduzida;
            case "Old School Red Ale":              return R.drawable.redale5reduzida;
            case "Leuven Red Ale":                  return R.drawable.redale6reduzida;
            case "Antuérpia Irish Red Ale":         return R.drawable.redale7reduzida;
            case "Brooklyn Brown Ale":              return R.drawable.brown1reduzida;
            case "Three Monkeys Brownie Ale":       return R.drawable.brown2reduzida;
            case "Fraga Brown":                     return R.drawable.brown3reduzida;
            case "Backer Brown":                    return R.drawable.brown4reduzida;
            case "Colorado Berthô":                 return R.drawable.brown5reduzida;
            case "Leffe Brune":                     return R.drawable.dubbel1reduzida;
            case "Chimay Red Cap":                  return R.drawable.dubbel2reduzida;
            case "La Trappe Dubbel":                return R.drawable.dubbel3reduzida;
            case "Bohemia Confraria":               return R.drawable.dubbel4reduzida;
            case "Westmalle Dubbel":                return R.drawable.dubbel5reduzida;
            case "Wäls Dubbel":                     return R.drawable.dubbel6reduzida;
            case "St. Feuillien Brune":             return R.drawable.dubbel7reduzida;
            case "Gauloise Bruin":                  return R.drawable.dubbel8reduzida;
            case "Hertog Jan Dubbel":               return R.drawable.dubbel9reduzida;
            case "Trappistes Rochefort 6":          return R.drawable.dubbel10reduzida;
            case "Leuven Dubbel":                   return R.drawable.dubbel11reduzida;
            case "Gouden Carolus Tripel":           return R.drawable.tripel1reduzida;
            case "Chimay Triple":                   return R.drawable.tripel2reduzida;
            case "La Trappe Tripel":                return R.drawable.tripel3reduzida;
            case "Leffe Tripel":                    return R.drawable.tripel4reduzida;
            case "Westmalle Tripel":                return R.drawable.tripel5reduzida;
            case "Wäls Trippel":                    return R.drawable.tripel6reduzida;
            case "Therezópolis Diamant":            return R.drawable.tripel7reduzida;
            case "Kasteel Tripel":                  return R.drawable.tripel8reduzida;
            case "St. Feuillien Tripel":            return R.drawable.tripel9reduzida;
            case "Mistura Clássica Beatus":         return R.drawable.tripel10reduzida;
            case "Trópica Veracruz":                return R.drawable.tripel11reduzida;
            case "Hertog Jan Tripel":               return R.drawable.tripel12reduzida;
            case "Baden Baden Tripel":              return R.drawable.tripel13reduzida;
            case "Tripel Karmeliet":                return R.drawable.tripel14reduzida;
            case "Maredsous 10 Tripel":             return R.drawable.tripel15reduzida;
            case "Antuérpia Belgian Tripel":        return R.drawable.tripel16reduzida;
            case "La Trappe Quadrupel":             return R.drawable.quadrupel1reduzida;
            case "Trappistes Rochefort 10":         return R.drawable.quadrupel2reduzida;
            case "Wäls Quadrupel":                  return R.drawable.quadrupel3reduzida;
            case "Gouden Carolus Cuvée van de Keizer Rood": return R.drawable.golden1reduzida;
            case "Delirium Tremens":                return R.drawable.golden2reduzida;
            case "Hoegaarden Grand Cru":            return R.drawable.golden3reduzida;
            case "La Guillotine":                   return R.drawable.golden4reduzida;
            case "Duvel":                           return R.drawable.golden5reduzida;
            case "Leffe 9º (Rituel 9)":             return R.drawable.golden6reduzida;
            case "Eisenbahn Strong Golden Ale":     return R.drawable.golden7reduzida;
            case "DaDo Bier Belgian Ale":           return R.drawable.golden8reduzida;
            case "Ashby Ale Forte":                 return R.drawable.golden9reduzida;
            case "Piraat":                          return R.drawable.golden10reduzida;
            case "Hocus Pocus Magic Trap":          return R.drawable.golden11reduzida;
            case "Bierland Strong Golden Ale":      return R.drawable.golden12reduzida;
            case "Birra del Borgo Stelle&Strisce":  return R.drawable.golden13reduzida;
            case "Birra del Borgo Cortigiana":      return R.drawable.golden14reduzida;
            case "Chimay Blue Cap":                 return R.drawable.darkale1reduzida;
            case "Gouden Carolus Classic":          return R.drawable.darkale2reduzida;
            case "Delirium Nocturnum":              return R.drawable.darkale3reduzida;
            case "Leffe Radieuse":                  return R.drawable.darkale4reduzida;
            case "La Trappe Jubilaris":             return R.drawable.darkale5reduzida;
            case "Gouden Carolus Ambrio":           return R.drawable.darkale6reduzida;
            case "Leffe Royale":                    return R.drawable.darkale7reduzida;
            case "Kasteel Donker":                  return R.drawable.darkale8reduzida;
            case "Gulden Draak":                    return R.drawable.darkale9reduzida;
            case "Hertog Jan Grand Prestige":       return R.drawable.darkale10reduzida;
            case "Trappistes Rochefort 8":          return R.drawable.darkale11reduzida;
            case "Maredsous 8 Bruin":               return R.drawable.darkale13reduzida;
            case "Birra del Borgo Maledetta":       return R.drawable.darkale14reduzida;
            case "Weihenstephaner Hefe Weissbier":  return R.drawable.weissbier1reduzida;
            case "Edelweiss Weissbier-Hefetrüb":    return R.drawable.weissbier2reduzida;
            case "Paulaner Hefe-Weissbier Naturtrüb": return R.drawable.weissbier3reduzida;
            case "Hofbräu Münchner Weisse":         return R.drawable.weissbier4reduzida;
            case "Therezopolis Elfenbein":          return R.drawable.weissbier5reduzida;
            case "Noi Bianca":                      return R.drawable.weissbier6reduzida;
            case "St. Gallen Weissbier":            return R.drawable.weissbier7reduzida;
            case "Baden Baden Weiss":               return R.drawable.weissbier8reduzida;
            case "Eisenbahn Weizenbier":            return R.drawable.weissbier9reduzida;
            case "Erdinger Weissbier":              return R.drawable.weissbier10reduzida;
            case "Colorado Appia":                  return R.drawable.weissbier11reduzida;
            case "Bohemia Weiss":                   return R.drawable.weissbier12reduzida;
            case "DaDo Bier Weiss":                 return R.drawable.weissbier13reduzida;
            case "Schornstein Weiss":               return R.drawable.weissbier14reduzida;
            case "Patagônia Weissbier":             return R.drawable.weissbier15reduzida;
            case "Primátor Weizenbier":             return R.drawable.weissbier16reduzida;
            case "Riegele´s Weisse":                return R.drawable.weissbier17reduzida;
            case "Ashby Weiss":                     return R.drawable.weissbier18reduzida;
            case "Brooklyn Wheat Beer":             return R.drawable.weissbier19reduzida;
            case "Coruja Alba Weizen":              return R.drawable.weissbier20reduzida;
            case "Moa Blanc":                       return R.drawable.weissbier21reduzida;
            case "Insana Weizen":                   return R.drawable.weissbier22reduzida;
            case "Fraga Weiss":                     return R.drawable.weissbier23reduzida;
            case "Backer Trigo":                    return R.drawable.weissbier24reduzida;
            case "Mistura Clássica Matilda":        return R.drawable.weissbier25reduzida;
            case "Bohemia 14 Weiss":                return R.drawable.weissbier26reduzida;
            case "Erdinger Urweisse":               return R.drawable.weissbier27reduzida;
            case "Brahma Extra Weiss":              return R.drawable.weissbier28reduzida;
            case "Franziskaner Hefe-Weissbier Naturtrüb": return R.drawable.weissbier29reduzida;
            case "Bierland Weizen":                 return R.drawable.weissbier30reduzida;
            case "Hacker Pschorr Weisse":           return R.drawable.weissbier31reduzida;
            case "Old School Weiss":                return R.drawable.weissbier32reduzida;
            case "Lado A":                          return R.drawable.weissbier33reduzida;
            case "Lado B":                          return R.drawable.weissbier34reduzida;
            case "Wieninger Hefe Weissbier":        return R.drawable.weissbier35reduzida;
            case "Brewpoint Weiss":                 return R.drawable.weissbier36reduzida;
            case "Antuérpia Weissbier":             return R.drawable.weissbier37reduzida;
            case "Riegele´s Augustus":              return R.drawable.weizenbock1reduzida;
            case "Erdinger Pikantus":               return R.drawable.weizenbock2reduzida;
            case "Zapp":                            return R.drawable.weizenbock3reduzida;
            case "Coruja Alba Weizenbock":          return R.drawable.weizenbock4reduzida;
            case "Erdinger Weissbier Dunkel":       return R.drawable.dunkelweizen1reduzida;
            case "Paulaner Hefe-Weissbier Dunkel":  return R.drawable.dunkelweizen2reduzida;
            case "Franziskaner Hefe-Weissbier Dunkel": return R.drawable.dunkelweizen3reduzida;
            case "Weltenburger Kloster Hefe-Weissbier Dunkel": return R.drawable.dunkelweizen4reduzida;
            case "Hoegaarden":                      return R.drawable.witbier1reduzida;
            case "DiTriguis":                       return R.drawable.witbier2reduzida;
            case "Bohemia Bela Rosa":               return R.drawable.witbier3reduzida;
            case "Therezópolis Or Blanc":           return R.drawable.witbier4reduzida;
            case "Vedett Extra White":              return R.drawable.witbier5reduzida;
            case "Faxe Witbier":                    return R.drawable.witbier6reduzida;
            case "Schornstein Witbier":             return R.drawable.witbier7reduzida;
            case "Baden Baden Witbier":             return R.drawable.witbier8reduzida;
            case "Wäls Witte":                      return R.drawable.witbier9reduzida;
            case "Blanche de Bruxelles":            return R.drawable.witbier10reduzida;
            case "Bierland Witbier":                return R.drawable.witbier11reduzida;
            case "Old School Witbier":              return R.drawable.witbier12reduzida;
            case "Leuven Blanche":                  return R.drawable.witbier13reduzida;
            case "Leuven Witbier":                  return R.drawable.witbier14reduzida;
            case "Mohave Yucca":                    return R.drawable.witbier15reduzida;
            case "Praya Witbier":                   return R.drawable.witbier16reduzida;
            case "Guinness Draught":                return R.drawable.stout1reduzida;
            case "Schornstein Imperial Stout":      return R.drawable.stout2reduzida;
            case "Baden Baden Stout":               return R.drawable.stout3reduzida;
            case "Murphy´s Draught Irish Stout":    return R.drawable.stout4reduzida;
            case "Super Bock Stout":                return R.drawable.stout5reduzida;
            case "Wensky Beer Lobisomem":           return R.drawable.stout6reduzida;
            case "St. Gallen Stout Porter":         return R.drawable.stout7reduzida;
            case "Colorado Ithaca":                 return R.drawable.stout8reduzida;
            case "Primátor Stout":                  return R.drawable.stout9reduzida;
            case "Noi Cioccolato":                  return R.drawable.stout10reduzida;
            case "Moa Imperial Stout":              return R.drawable.stout11reduzida;
            case "Mistura Clássica Panhead":        return R.drawable.stout12reduzida;
            case "Bohemia Oito e Um":               return R.drawable.stout13reduzida;
            case "Wäls Petroleum":                  return R.drawable.stout14reduzida;
            case "Bierland Russian Imperial Stout": return R.drawable.stout15reduzida;
            case "Fuller´s Black Cab Stout":        return R.drawable.stout16reduzida;
            case "Fuller´s Imperial Stout":         return R.drawable.stout17reduzida;
            case "Colorado Demoiselle":             return R.drawable.porter1reduzida;
            case "3 Lobos Bravo":                   return R.drawable.porter2reduzida;
            case "Ashby Porter":                    return R.drawable.porter3reduzida;
            case "Insana Chocolate Porter":         return R.drawable.porter4reduzida;
            case "Trópica Macau":                   return R.drawable.porter5reduzida;
            case "Double Zuzi":                     return R.drawable.porter6reduzida;
            case "Fuller´s London Porter":          return R.drawable.porter7reduzida;

            default:                                return R.drawable.ic_not_founddark;
        }

    }

}